#!/usr/bin/env python3
"""Batch generate proficiency icons for Arcadia.

Pipeline per proficiency:
  1. Call Gemini API for raw image (green screen)
  2. Remove green background
  3. Composite transparent subject onto pre-existing category base
  4. Save final icon

Bases are pre-existing at assets/textures/ui/proficiencies/subjects/v1/{grey,red,green,yellow}.png
— they are NOT regenerated by this script.

Usage:
    python3 scripts/tools/generate_proficiency_icons.py
    python3 scripts/tools/generate_proficiency_icons.py --only=str
    python3 scripts/tools/generate_proficiency_icons.py --dry-run
    python3 scripts/tools/generate_proficiency_icons.py --skip-generate
"""

import sys
import time
import argparse
from pathlib import Path

# Allow importing from sibling scripts
sys.path.insert(0, str(Path(__file__).parent))
from generate_icon import generate_icon
from generate_skill_icons import remove_green_background, composite_onto_base

from PIL import Image

# ---------------------------------------------------------------------------
# Output paths
# ---------------------------------------------------------------------------
ASSET_ROOT = Path(__file__).parent.parent.parent / "assets/textures/ui/proficiencies"
FINAL_DIR = ASSET_ROOT
BASES_DIR = ASSET_ROOT / "subjects/v1"
SUBJECTS_DIR = ASSET_ROOT / "subjects/v1/icons"
RAW_DIR = ASSET_ROOT / "subjects/v1/icons"

# ---------------------------------------------------------------------------
# Category → base image mapping
# ---------------------------------------------------------------------------
# Bases are pre-existing PNGs; this maps category name to filename stem
CATEGORY_BASE = {
    "attribute":  "grey.png",
    "weapon":     "red.png",
    "gathering":  "green.png",
    "production": "yellow.png",
}

# ---------------------------------------------------------------------------
# Proficiency definitions
# ---------------------------------------------------------------------------
PROMPT_TEMPLATE = (
    "Game UI icon of {description}, "
    "warm pale gold metallic emblem, subtle gold tint, "
    "smooth gradient from light warm gold to slightly darker gold, "
    "very thin subtle outline, soft edges, opaque filled shape, "
    "like a luxury car badge, compact square composition, "
    "no text, no letters, no frame, no background shape, "
    "just the warm gold metallic symbol on plain bright green background, centered"
)

# (prof_id, category, prompt_description, tolerance)
PROFICIENCIES = [
    ("str",   "attribute", "a raised clenched fist, compact stylized logo", 40),
    ("int",   "attribute", "an open book with a star above it, compact badge shape", 40),
    ("dex",   "attribute", "a single elegant feather quill, compact badge", 40),
    ("wis",   "attribute", "an eye with rays above it, compact badge shape", 40),
    ("bow",   "weapon",    "a bow with arrow, compact side view badge", 40),
    ("spear", "weapon",    "a single spear with pointed tip, diagonal, compact badge", 40),
]

# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def get_base_path(category: str) -> Path:
    filename = CATEGORY_BASE[category]
    return BASES_DIR / filename


def get_raw_path(prof_id: str) -> Path:
    return RAW_DIR / f"{prof_id}_raw.png"


def get_subject_path(prof_id: str) -> Path:
    return SUBJECTS_DIR / f"{prof_id}.png"


def get_final_path(prof_id: str) -> Path:
    return FINAL_DIR / f"{prof_id}.png"


def build_prompt(description: str) -> str:
    return PROMPT_TEMPLATE.format(description=description)


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def ensure_dirs():
    for d in (FINAL_DIR, SUBJECTS_DIR):
        d.mkdir(parents=True, exist_ok=True)


def process_proficiency(prof_id: str, category: str, description: str, tolerance: int,
                        skip_generate: bool, dry_run: bool):
    prompt = build_prompt(description)
    raw_path = get_raw_path(prof_id)
    subject_path = get_subject_path(prof_id)
    final_path = get_final_path(prof_id)
    base_path = get_base_path(category)

    if dry_run:
        print(f"\n[{prof_id}]")
        print(f"  category : {category}")
        print(f"  tolerance: {tolerance}")
        print(f"  prompt   : {prompt}")
        print(f"  raw      : {raw_path}")
        print(f"  subject  : {subject_path}")
        print(f"  final    : {final_path}")
        print(f"  base     : {base_path}")
        return

    print(f"\n[{prof_id}] processing...")

    # Step 1: Generate raw image from Gemini (unless skipping)
    if not skip_generate:
        if raw_path.exists():
            print(f"  [generate] skip (exists): {raw_path}")
        else:
            print(f"  [generate] calling Gemini API...")
            try:
                generate_icon(prompt, str(raw_path), size="512x512", bg_remove=False)
            except SystemExit:
                print(f"  [FAILED] API call failed for {prof_id}, skipping")
                return
            print(f"  [generate] saved raw: {raw_path}")
            time.sleep(2)  # rate limit
    else:
        if not raw_path.exists():
            print(f"  [generate] WARNING: raw file missing, skipping: {raw_path}")
            return

    # Step 2: Remove green background
    print(f"  [bg-remove] green-dominant keying...")
    raw_img = Image.open(str(raw_path)).convert("RGBA")
    subject_img = remove_green_background(raw_img)
    subject_path.parent.mkdir(parents=True, exist_ok=True)
    subject_img.save(str(subject_path), "PNG")
    print(f"  [bg-remove] saved subject: {subject_path}")

    # Step 3: Load pre-existing category base
    if not base_path.exists():
        print(f"  [composite] ERROR: base not found: {base_path}")
        print(f"  [composite] Expected pre-existing base at: {base_path}")
        return
    base_img = Image.open(str(base_path)).convert("RGBA")

    # Step 4: Composite subject onto base
    print(f"  [composite] compositing onto {category} base ({base_path.name})...")
    final_img = composite_onto_base(subject_img, base_img)
    final_path.parent.mkdir(parents=True, exist_ok=True)
    final_img.save(str(final_path), "PNG")
    print(f"  [composite] saved final: {final_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--skip-generate", action="store_true",
                        help="Reuse existing raw images, only re-composite")
    parser.add_argument("--only", metavar="PROF_ID",
                        help="Generate a single proficiency only (e.g. --only=str)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print prompts and paths without calling the API")
    args = parser.parse_args()

    if not args.dry_run:
        ensure_dirs()

    # Filter if --only specified
    profs_to_run = PROFICIENCIES
    if args.only:
        profs_to_run = [p for p in PROFICIENCIES if p[0] == args.only]
        if not profs_to_run:
            valid_ids = [p[0] for p in PROFICIENCIES]
            print(f"ERROR: unknown proficiency '{args.only}'. Valid IDs: {valid_ids}")
            sys.exit(1)

    if args.dry_run:
        print("=== DRY RUN — no API calls will be made ===\n")
        print("Category bases (pre-existing, not regenerated):")
        seen = set()
        for _, category, _, _ in profs_to_run:
            if category not in seen:
                seen.add(category)
                base = get_base_path(category)
                exists = "EXISTS" if base.exists() else "MISSING"
                print(f"  [{exists}] {base}")
        print(f"\nProficiencies ({len(profs_to_run)}):")
    else:
        print("=== Verifying category bases ===")
        missing_bases = []
        seen = set()
        for _, category, _, _ in profs_to_run:
            if category not in seen:
                seen.add(category)
                base = get_base_path(category)
                if base.exists():
                    print(f"  [base] found: {base}")
                else:
                    print(f"  [base] MISSING: {base}")
                    missing_bases.append(base)
        if missing_bases:
            print("\nERROR: missing base images. Generate them with generate_proficiency_bases.py")
            sys.exit(1)

    for prof_id, category, description, tolerance in profs_to_run:
        process_proficiency(
            prof_id=prof_id,
            category=category,
            description=description,
            tolerance=tolerance,
            skip_generate=args.skip_generate,
            dry_run=args.dry_run,
        )

    if not args.dry_run:
        print("\nDone.")


if __name__ == "__main__":
    main()
